Set Shell zsh

Require redis-cli 

Output demo.gif

Set Theme "Rose Pine"

Set FontSize 36
Set Width 1065
Set Height 810


Type "redis-cli"

Sleep 300ms

Enter

Sleep 500ms

Type "PING" 

Sleep 500ms

Enter

Sleep 500ms

Type "echo 'Hello World!'" 

Sleep 500ms

Enter

Sleep 1s

Type "SET myKey 1234 EX 2"

Sleep 500ms

Enter

Sleep 100ms

Type "GET myKey"

Sleep 500ms

Enter

Sleep 1s

Type "GET myKey"

Sleep 500ms

Enter

Sleep 2s

